-- Run this ONCE in Supabase SQL Editor for the BLACK-DEAR-TIPS project.
-- This creates the private server-side payment/order table used by the Vercel API.

create table if not exists public.vip_payments (
  id bigint generated by default as identity primary key,
  reference text not null unique,
  plan text not null,
  plan_name text not null,
  amount numeric(12,2) not null,
  duration_days integer not null,
  customer_name text not null,
  customer_email text not null,
  phone_number text not null,
  status text not null default 'pending',
  payment_key text,
  wave_transaction_id text,
  checkout_request_id text,
  receipt_number text,
  failure_reason text,
  access_token text not null unique,
  paid_at timestamptz,
  vip_expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists vip_payments_reference_idx on public.vip_payments(reference);
create index if not exists vip_payments_payment_key_idx on public.vip_payments(payment_key);
create index if not exists vip_payments_access_token_idx on public.vip_payments(access_token);
create index if not exists vip_payments_status_idx on public.vip_payments(status);

alter table public.vip_payments enable row level security;

-- No public policies are created intentionally. The Vercel API uses the Supabase service-role key server-side.

-- Keep updated_at current when rows are changed.
create or replace function public.set_vip_payments_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists vip_payments_updated_at on public.vip_payments;
create trigger vip_payments_updated_at
before update on public.vip_payments
for each row execute function public.set_vip_payments_updated_at();
